'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace AnulacionTimbre
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", ConfigurationName:="AnulacionTimbre.ICancelacion")>  _
    Public Interface ICancelacion
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (CancelacionFiscalRequest) del mensaje CancelacionFiscalRequest no coincide con el valor predeterminado (Cancelar)
        <System.ServiceModel.OperationContractAttribute(Action:="urn:reachcore.com:services:api:ws:pacservices:6.0/ICancelacion/Cancelar", ReplyAction:="urn:reachcore.com:services:api:ws:pacservices:6.0/ICancelacion/CancelarResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MessageCode))>  _
        Function Cancelar(ByVal request As AnulacionTimbre.CancelacionFiscalRequest) As AnulacionTimbre.CancelacionFiscalResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (FolioStatusRequest) del mensaje FolioStatusRequest no coincide con el valor predeterminado (GetFolioStatusDetail)
        <System.ServiceModel.OperationContractAttribute(Action:="urn:reachcore.com:services:api:ws:pacservices:6.0/ICancelacion/GetFolioStatusDeta"& _ 
            "il", ReplyAction:="urn:reachcore.com:services:api:ws:pacservices:6.0/ICancelacion/GetFolioStatusDeta"& _ 
            "ilResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MessageCode))>  _
        Function GetFolioStatusDetail(ByVal request As AnulacionTimbre.FolioStatusRequest) As AnulacionTimbre.FolioStatusResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (TransactionStatusRequest) del mensaje TransactionStatusRequest no coincide con el valor predeterminado (GetTransactionStatusDetail)
        <System.ServiceModel.OperationContractAttribute(Action:="urn:reachcore.com:services:api:ws:pacservices:6.0/ICancelacion/GetTransactionStat"& _ 
            "usDetail", ReplyAction:="urn:reachcore.com:services:api:ws:pacservices:6.0/ICancelacion/GetTransactionStat"& _ 
            "usDetailResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MessageCode))>  _
        Function GetTransactionStatusDetail(ByVal request As AnulacionTimbre.TransactionStatusRequest) As AnulacionTimbre.TransactionStatusResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (CancelarSolicitudFirmadaRequest) del mensaje CancelarSolicitudFirmadaRequest no coincide con el valor predeterminado (CancelarSolicitudFirmada)
        <System.ServiceModel.OperationContractAttribute(Action:="urn:reachcore.com:services:api:ws:pacservices:6.0/ICancelacion/CancelarSolicitudF"& _ 
            "irmada", ReplyAction:="urn:reachcore.com:services:api:ws:pacservices:6.0/ICancelacion/CancelarSolicitudF"& _ 
            "irmadaResponse"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(MessageCode))>  _
        Function CancelarSolicitudFirmada(ByVal request As AnulacionTimbre.CancelarSolicitudFirmadaRequest) As AnulacionTimbre.CancelarSolicituFirmadaResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0")>  _
    Partial Public Class CancelFolio
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uUIDField As String
        
        Private reasonField As String
        
        Private uUIDSubstituteField As String
        
        Private totalField As String
        
        Private recipientRFCField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
                Me.RaisePropertyChanged("UUID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Reason() As String
            Get
                Return Me.reasonField
            End Get
            Set
                Me.reasonField = value
                Me.RaisePropertyChanged("Reason")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property UUIDSubstitute() As String
            Get
                Return Me.uUIDSubstituteField
            End Get
            Set
                Me.uUIDSubstituteField = value
                Me.RaisePropertyChanged("UUIDSubstitute")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Total() As String
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
                Me.RaisePropertyChanged("Total")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property RecipientRFC() As String
            Get
                Return Me.recipientRFCField
            End Get
            Set
                Me.recipientRFCField = value
                Me.RaisePropertyChanged("RecipientRFC")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0")>  _
    Partial Public Class FoliosToQuery
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uUIDField As String
        
        Private recipientRFCField As String
        
        Private totalField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
                Me.RaisePropertyChanged("UUID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property RecipientRFC() As String
            Get
                Return Me.recipientRFCField
            End Get
            Set
                Me.recipientRFCField = value
                Me.RaisePropertyChanged("RecipientRFC")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Total() As String
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
                Me.RaisePropertyChanged("Total")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0")>  _
    Partial Public Class FolioFiscalDetail
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uUIDField As System.Guid
        
        Private requestSentToSATField As Boolean
        
        Private resultCodeField As String
        
        Private resultMessageField As String
        
        Private uUIDStatusField As StateQueryResponse
        
        Private relatedUUIDsField() As FolioFiscalDetail
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property UUID() As System.Guid
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
                Me.RaisePropertyChanged("UUID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property RequestSentToSAT() As Boolean
            Get
                Return Me.requestSentToSATField
            End Get
            Set
                Me.requestSentToSATField = value
                Me.RaisePropertyChanged("RequestSentToSAT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property ResultCode() As String
            Get
                Return Me.resultCodeField
            End Get
            Set
                Me.resultCodeField = value
                Me.RaisePropertyChanged("ResultCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property ResultMessage() As String
            Get
                Return Me.resultMessageField
            End Get
            Set
                Me.resultMessageField = value
                Me.RaisePropertyChanged("ResultMessage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property UUIDStatus() As StateQueryResponse
            Get
                Return Me.uUIDStatusField
            End Get
            Set
                Me.uUIDStatusField = value
                Me.RaisePropertyChanged("UUIDStatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=5)>  _
        Public Property RelatedUUIDs() As FolioFiscalDetail()
            Get
                Return Me.relatedUUIDsField
            End Get
            Set
                Me.relatedUUIDsField = value
                Me.RaisePropertyChanged("RelatedUUIDs")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0")>  _
    Partial Public Class StateQueryResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private statusCodeField As String
        
        Private isCancellableField As String
        
        Private stateField As String
        
        Private cancellationStatusField As String
        
        Private queryDateField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property StatusCode() As String
            Get
                Return Me.statusCodeField
            End Get
            Set
                Me.statusCodeField = value
                Me.RaisePropertyChanged("StatusCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property IsCancellable() As String
            Get
                Return Me.isCancellableField
            End Get
            Set
                Me.isCancellableField = value
                Me.RaisePropertyChanged("IsCancellable")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property State() As String
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
                Me.RaisePropertyChanged("State")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property CancellationStatus() As String
            Get
                Return Me.cancellationStatusField
            End Get
            Set
                Me.cancellationStatusField = value
                Me.RaisePropertyChanged("CancellationStatus")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property QueryDate() As Date
            Get
                Return Me.queryDateField
            End Get
            Set
                Me.queryDateField = value
                Me.RaisePropertyChanged("QueryDate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ErrorMessageCode)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0")>  _
    Partial Public Class MessageCode
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private codeField As String
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
                Me.RaisePropertyChanged("Code")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("Message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0")>  _
    Partial Public Class ErrorMessageCode
        Inherits MessageCode
        
        Private targetField As String
        
        Private detailsField As String
        
        Private innerErrorsField() As ErrorMessageCode
        
        Private moreInfoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Target() As String
            Get
                Return Me.targetField
            End Get
            Set
                Me.targetField = value
                Me.RaisePropertyChanged("Target")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Details() As String
            Get
                Return Me.detailsField
            End Get
            Set
                Me.detailsField = value
                Me.RaisePropertyChanged("Details")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=2),  _
         System.Xml.Serialization.XmlArrayItemAttribute("Error")>  _
        Public Property InnerErrors() As ErrorMessageCode()
            Get
                Return Me.innerErrorsField
            End Get
            Set
                Me.innerErrorsField = value
                Me.RaisePropertyChanged("InnerErrors")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property MoreInfo() As String
            Get
                Return Me.moreInfoField
            End Get
            Set
                Me.moreInfoField = value
                Me.RaisePropertyChanged("MoreInfo")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0")>  _
    Partial Public Class TransactionProperty
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private keyField As String
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
                Me.RaisePropertyChanged("Key")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
                Me.RaisePropertyChanged("Value")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelacionFiscalRequest", WrapperNamespace:="urn:reachcore.com:services:api:ws:pacservices:6.0", IsWrapped:=true)>  _
    Partial Public Class CancelacionFiscalRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.reachcore.com/CFDI/customHeaders")>  _
        Public ApiKey As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=0)>  _
        Public RFC As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=1)>  _
        Public Folios() As AnulacionTimbre.CancelFolio
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=2)>  _
        Public TransactionProperties() As AnulacionTimbre.TransactionProperty
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ApiKey As String, ByVal RFC As String, ByVal Folios() As AnulacionTimbre.CancelFolio, ByVal TransactionProperties() As AnulacionTimbre.TransactionProperty)
            MyBase.New
            Me.ApiKey = ApiKey
            Me.RFC = RFC
            Me.Folios = Folios
            Me.TransactionProperties = TransactionProperties
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelacionFiscalResponse", WrapperNamespace:="urn:reachcore.com:services:api:ws:pacservices:6.0", IsWrapped:=true)>  _
    Partial Public Class CancelacionFiscalResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=0)>  _
        Public [Error] As AnulacionTimbre.ErrorMessageCode
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=1)>  _
        Public OnError As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=2)>  _
        Public TrackingId As System.Guid
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [Error] As AnulacionTimbre.ErrorMessageCode, ByVal OnError As Boolean, ByVal TrackingId As System.Guid)
            MyBase.New
            Me.[Error] = [Error]
            Me.OnError = OnError
            Me.TrackingId = TrackingId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="FolioStatusRequest", WrapperNamespace:="urn:reachcore.com:services:api:ws:pacservices:6.0", IsWrapped:=true)>  _
    Partial Public Class FolioStatusRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.reachcore.com/CFDI/customHeaders")>  _
        Public ApiKey As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=0)>  _
        Public UUID As System.Guid
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ApiKey As String, ByVal UUID As System.Guid)
            MyBase.New
            Me.ApiKey = ApiKey
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="FolioStatusResponse", WrapperNamespace:="urn:reachcore.com:services:api:ws:pacservices:6.0", IsWrapped:=true)>  _
    Partial Public Class FolioStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=0)>  _
        Public OnError As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=1)>  _
        Public [Error] As AnulacionTimbre.ErrorMessageCode
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=2)>  _
        Public SatSentRequest As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=3)>  _
        Public ResultCode As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=4)>  _
        Public ResultMessage As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=5)>  _
        Public UUID As System.Guid
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=6)>  _
        Public UUIDStatus As AnulacionTimbre.StateQueryResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=7)>  _
        Public RelatedUUIDs() As AnulacionTimbre.FolioFiscalDetail
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal OnError As Boolean, ByVal [Error] As AnulacionTimbre.ErrorMessageCode, ByVal SatSentRequest As Boolean, ByVal ResultCode As String, ByVal ResultMessage As String, ByVal UUID As System.Guid, ByVal UUIDStatus As AnulacionTimbre.StateQueryResponse, ByVal RelatedUUIDs() As AnulacionTimbre.FolioFiscalDetail)
            MyBase.New
            Me.OnError = OnError
            Me.[Error] = [Error]
            Me.SatSentRequest = SatSentRequest
            Me.ResultCode = ResultCode
            Me.ResultMessage = ResultMessage
            Me.UUID = UUID
            Me.UUIDStatus = UUIDStatus
            Me.RelatedUUIDs = RelatedUUIDs
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TransactionStatusRequest", WrapperNamespace:="urn:reachcore.com:services:api:ws:pacservices:6.0", IsWrapped:=true)>  _
    Partial Public Class TransactionStatusRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.reachcore.com/CFDI/customHeaders")>  _
        Public ApiKey As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=0)>  _
        Public TrackingId As System.Guid
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ApiKey As String, ByVal TrackingId As System.Guid)
            MyBase.New
            Me.ApiKey = ApiKey
            Me.TrackingId = TrackingId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="TransactionStatusResponse", WrapperNamespace:="urn:reachcore.com:services:api:ws:pacservices:6.0", IsWrapped:=true)>  _
    Partial Public Class TransactionStatusResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=0)>  _
        Public OnError As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=1)>  _
        Public [Error] As AnulacionTimbre.ErrorMessageCode
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=2)>  _
        Public ErrorMessage As AnulacionTimbre.ErrorMessageCode
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=3)>  _
        Public TotalUUIDs As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=4)>  _
        Public UUIDsSentToSAT As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=5)>  _
        Public UUIDsRejectedSAT As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=6)>  _
        Public Finished As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=7)>  _
        Public UUIDs() As AnulacionTimbre.FolioFiscalDetail
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal OnError As Boolean, ByVal [Error] As AnulacionTimbre.ErrorMessageCode, ByVal ErrorMessage As AnulacionTimbre.ErrorMessageCode, ByVal TotalUUIDs As Integer, ByVal UUIDsSentToSAT As Integer, ByVal UUIDsRejectedSAT As Integer, ByVal Finished As Boolean, ByVal UUIDs() As AnulacionTimbre.FolioFiscalDetail)
            MyBase.New
            Me.OnError = OnError
            Me.[Error] = [Error]
            Me.ErrorMessage = ErrorMessage
            Me.TotalUUIDs = TotalUUIDs
            Me.UUIDsSentToSAT = UUIDsSentToSAT
            Me.UUIDsRejectedSAT = UUIDsRejectedSAT
            Me.Finished = Finished
            Me.UUIDs = UUIDs
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarSolicitudFirmadaRequest", WrapperNamespace:="urn:reachcore.com:services:api:ws:pacservices:6.0", IsWrapped:=true)>  _
    Partial Public Class CancelarSolicitudFirmadaRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://www.reachcore.com/CFDI/customHeaders")>  _
        Public ApiKey As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=0)>  _
        Public SignedApplication As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=1)>  _
        Public UUIDs() As AnulacionTimbre.FoliosToQuery
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=2)>  _
        Public TransactionProperties() As AnulacionTimbre.TransactionProperty
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ApiKey As String, ByVal SignedApplication As String, ByVal UUIDs() As AnulacionTimbre.FoliosToQuery, ByVal TransactionProperties() As AnulacionTimbre.TransactionProperty)
            MyBase.New
            Me.ApiKey = ApiKey
            Me.SignedApplication = SignedApplication
            Me.UUIDs = UUIDs
            Me.TransactionProperties = TransactionProperties
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="CancelarSolicituFirmadaResponse", WrapperNamespace:="urn:reachcore.com:services:api:ws:pacservices:6.0", IsWrapped:=true)>  _
    Partial Public Class CancelarSolicituFirmadaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=0)>  _
        Public OnError As Boolean
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=1)>  _
        Public [Error] As AnulacionTimbre.ErrorMessageCode
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="urn:reachcore.com:services:api:ws:pacservices:6.0", Order:=2)>  _
        Public TrackingId As System.Guid
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal OnError As Boolean, ByVal [Error] As AnulacionTimbre.ErrorMessageCode, ByVal TrackingId As System.Guid)
            MyBase.New
            Me.OnError = OnError
            Me.[Error] = [Error]
            Me.TrackingId = TrackingId
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICancelacionChannel
        Inherits AnulacionTimbre.ICancelacion, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CancelacionClient
        Inherits System.ServiceModel.ClientBase(Of AnulacionTimbre.ICancelacion)
        Implements AnulacionTimbre.ICancelacion
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AnulacionTimbre_ICancelacion_Cancelar(ByVal request As AnulacionTimbre.CancelacionFiscalRequest) As AnulacionTimbre.CancelacionFiscalResponse Implements AnulacionTimbre.ICancelacion.Cancelar
            Return MyBase.Channel.Cancelar(request)
        End Function
        
        Public Function Cancelar(ByVal ApiKey As String, ByVal RFC As String, ByVal Folios() As AnulacionTimbre.CancelFolio, ByVal TransactionProperties() As AnulacionTimbre.TransactionProperty, <System.Runtime.InteropServices.OutAttribute()> ByRef OnError As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef TrackingId As System.Guid) As AnulacionTimbre.ErrorMessageCode
            Dim inValue As AnulacionTimbre.CancelacionFiscalRequest = New AnulacionTimbre.CancelacionFiscalRequest()
            inValue.ApiKey = ApiKey
            inValue.RFC = RFC
            inValue.Folios = Folios
            inValue.TransactionProperties = TransactionProperties
            Dim retVal As AnulacionTimbre.CancelacionFiscalResponse = CType(Me,AnulacionTimbre.ICancelacion).Cancelar(inValue)
            OnError = retVal.OnError
            TrackingId = retVal.TrackingId
            Return retVal.[Error]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AnulacionTimbre_ICancelacion_GetFolioStatusDetail(ByVal request As AnulacionTimbre.FolioStatusRequest) As AnulacionTimbre.FolioStatusResponse Implements AnulacionTimbre.ICancelacion.GetFolioStatusDetail
            Return MyBase.Channel.GetFolioStatusDetail(request)
        End Function
        
        Public Function GetFolioStatusDetail(ByVal ApiKey As String, ByRef UUID As System.Guid, <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As AnulacionTimbre.ErrorMessageCode, <System.Runtime.InteropServices.OutAttribute()> ByRef SatSentRequest As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef ResultCode As String, <System.Runtime.InteropServices.OutAttribute()> ByRef ResultMessage As String, <System.Runtime.InteropServices.OutAttribute()> ByRef UUIDStatus As AnulacionTimbre.StateQueryResponse, <System.Runtime.InteropServices.OutAttribute()> ByRef RelatedUUIDs() As AnulacionTimbre.FolioFiscalDetail) As Boolean
            Dim inValue As AnulacionTimbre.FolioStatusRequest = New AnulacionTimbre.FolioStatusRequest()
            inValue.ApiKey = ApiKey
            inValue.UUID = UUID
            Dim retVal As AnulacionTimbre.FolioStatusResponse = CType(Me,AnulacionTimbre.ICancelacion).GetFolioStatusDetail(inValue)
            [Error] = retVal.[Error]
            SatSentRequest = retVal.SatSentRequest
            ResultCode = retVal.ResultCode
            ResultMessage = retVal.ResultMessage
            UUID = retVal.UUID
            UUIDStatus = retVal.UUIDStatus
            RelatedUUIDs = retVal.RelatedUUIDs
            Return retVal.OnError
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AnulacionTimbre_ICancelacion_GetTransactionStatusDetail(ByVal request As AnulacionTimbre.TransactionStatusRequest) As AnulacionTimbre.TransactionStatusResponse Implements AnulacionTimbre.ICancelacion.GetTransactionStatusDetail
            Return MyBase.Channel.GetTransactionStatusDetail(request)
        End Function
        
        Public Function GetTransactionStatusDetail(ByVal ApiKey As String, ByVal TrackingId As System.Guid, <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As AnulacionTimbre.ErrorMessageCode, <System.Runtime.InteropServices.OutAttribute()> ByRef ErrorMessage As AnulacionTimbre.ErrorMessageCode, <System.Runtime.InteropServices.OutAttribute()> ByRef TotalUUIDs As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef UUIDsSentToSAT As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef UUIDsRejectedSAT As Integer, <System.Runtime.InteropServices.OutAttribute()> ByRef Finished As Boolean, <System.Runtime.InteropServices.OutAttribute()> ByRef UUIDs() As AnulacionTimbre.FolioFiscalDetail) As Boolean
            Dim inValue As AnulacionTimbre.TransactionStatusRequest = New AnulacionTimbre.TransactionStatusRequest()
            inValue.ApiKey = ApiKey
            inValue.TrackingId = TrackingId
            Dim retVal As AnulacionTimbre.TransactionStatusResponse = CType(Me,AnulacionTimbre.ICancelacion).GetTransactionStatusDetail(inValue)
            [Error] = retVal.[Error]
            ErrorMessage = retVal.ErrorMessage
            TotalUUIDs = retVal.TotalUUIDs
            UUIDsSentToSAT = retVal.UUIDsSentToSAT
            UUIDsRejectedSAT = retVal.UUIDsRejectedSAT
            Finished = retVal.Finished
            UUIDs = retVal.UUIDs
            Return retVal.OnError
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function AnulacionTimbre_ICancelacion_CancelarSolicitudFirmada(ByVal request As AnulacionTimbre.CancelarSolicitudFirmadaRequest) As AnulacionTimbre.CancelarSolicituFirmadaResponse Implements AnulacionTimbre.ICancelacion.CancelarSolicitudFirmada
            Return MyBase.Channel.CancelarSolicitudFirmada(request)
        End Function
        
        Public Function CancelarSolicitudFirmada(ByVal ApiKey As String, ByVal SignedApplication As String, ByVal UUIDs() As AnulacionTimbre.FoliosToQuery, ByVal TransactionProperties() As AnulacionTimbre.TransactionProperty, <System.Runtime.InteropServices.OutAttribute()> ByRef [Error] As AnulacionTimbre.ErrorMessageCode, <System.Runtime.InteropServices.OutAttribute()> ByRef TrackingId As System.Guid) As Boolean
            Dim inValue As AnulacionTimbre.CancelarSolicitudFirmadaRequest = New AnulacionTimbre.CancelarSolicitudFirmadaRequest()
            inValue.ApiKey = ApiKey
            inValue.SignedApplication = SignedApplication
            inValue.UUIDs = UUIDs
            inValue.TransactionProperties = TransactionProperties
            Dim retVal As AnulacionTimbre.CancelarSolicituFirmadaResponse = CType(Me,AnulacionTimbre.ICancelacion).CancelarSolicitudFirmada(inValue)
            [Error] = retVal.[Error]
            TrackingId = retVal.TrackingId
            Return retVal.OnError
        End Function
    End Class
End Namespace
